apiVersion: v1
kind: Service
metadata:
  name: utopia-postgres
  labels:
    app: utopia-postgres
spec:
  type: ClusterIP
  selector:
    app: utopia-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
